# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'
[env]
TERM = "alacritty-direct"

[font]
size = 13.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold-Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[general]
live_config_reload = true
